namespace Aiursoft.CSTools.Models;

public static class Mime
{
    private record MimeMapping(string ContentType, string Icon);

    private static readonly Dictionary<string, MimeMapping> ExtensionMap = new()
    {
        { "7z", new("application/x-7z-compressed", "application-x-archive.svg") },
        { "3gp", new("video/3gpp", "video-x-generic.svg") },
        { "3g2", new("video/3gpp2", "video-x-generic.svg") },
        { "aac", new("audio/aac", "audio-x-generic.svg") },
        { "abw", new("application/x-abiword", "x-office-document.svg") },
        { "a", new("application/octet-stream", "application-octet-stream.svg") },
        { "ai", new("application/postscript", "application-illustrator.svg") },
        { "apk", new("application/vnd.android.package-archive", "application-apk.svg") },
        { "arc", new("application/x-freearc", "application-x-archive.svg") },
        { "art", new("image/x-jg", "image-x-generic.svg") },
        { "avi", new("video/x-msvideo", "video-x-generic.svg") },
        { "azw", new("application/vnd.amazon.ebook", "application-vnd.amazon.ebook.svg") },
        { "bak", new("application/x-trash", "application-x-trash.svg") },
        { "bin", new("application/octet-stream", "application-octet-stream.svg") },
        { "blend", new("application/x-blender", "application-x-blender.svg") },
        { "bmp", new("image/bmp", "image-bmp.svg") },
        { "bz", new("application/x-bzip", "application-x-bzip.svg") },
        { "bz2", new("application/x-bzip2", "application-x-bzip.svg") },
        { "c", new("text/plain", "text-x-c.svg") },
        { "cab", new("application/vnd.ms-cab-compressed", "application-vnd.ms-cab-compressed.svg") },
        { "chm", new("application/vnd.ms-htmlhelp", "application-vnd.ms-htmlhelp.svg") },
        { "class", new("application/x-java-applet", "application-x-java.svg") },
        { "cls", new("text/x-tex", "text-x-tex.svg") },
        { "cmake", new("text/plain", "text-x-cmake.svg") },
        { "coffee", new("text/coffeescript", "application-vnd.coffeescript.svg") },
        { "conf", new("text/plain", "text-x-script.svg") },
        { "cpp", new("text/plain", "text-x-cpp.svg") },
        { "csh", new("application/x-csh", "application-x-shellscript.svg") },
        { "cs", new("text/plain", "text-x-csharp.svg") },
        { "css", new("text/css", "text-css.svg") },
        { "csv", new("text/csv", "x-office-spreadsheet.svg") },
        { "dcm", new("application/dicom", "application-dicom.svg") },
        { "deb", new("application/vnd.debian.binary-package", "application-x-deb.svg") },
        { "deploy", new("application/octet-stream", "application-octet-stream.svg") },
        { "djv", new("image/vnd.djvu", "image-vnd.djvu.svg") },
        { "djvu", new("image/vnd.djvu", "image-vnd.djvu.svg") },
        { "dll", new("application/x-msdownload", "application-x-sharedlib.svg") },
        { "doc", new("application/msword", "application-vnd.ms-word.svg") },
        { "dockerfile", new("text/plain", "text-dockerfile.svg") },
        { "docx", new("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application-vnd.openxmlformats-officedocument.wordprocessingml.document.svg") },
        { "dotx", new("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "application-vnd.openxmlformats-officedocument.wordprocessingml.template.svg") },
        { "dwg", new("image/vnd.dwg", "image-vnd.dwg.svg") },
        { "eml", new("message/rfc822", "message-rfc822.svg") },
        { "env", new("text/plain", "application-x-theme.svg") },
        { "eot", new("application/vnd.ms-fontobject", "font-x-generic.svg") },
        { "eps", new("application/postscript", "application-postscript.svg") },
        { "eps2", new("application/postscript", "application-postscript.svg") },
        { "eps3", new("application/postscript", "application-postscript.svg") },
        { "epsf", new("application/postscript", "application-postscript.svg") },
        { "epsi", new("application/postscript", "application-postscript.svg") },
        { "epub", new("application/epub+zip", "application-epub+zip.svg") },
        { "exe", new("application/x-msdownload", "application-x-msdownload.svg") },
        { "f", new("text/plain", "text-x-fortran.svg") },
        { "f90", new("text/plain", "text-x-fortran.svg") },
        { "flac", new("audio/flac", "audio-x-generic.svg") },
        { "flatpak", new("application/vnd.flatpak", "application-vnd.flatpak.svg") },
        { "gdoc", new("application/vnd.google-apps.document", "gddoc.svg") },
        { "ggb", new("application/vnd.geogebra.file", "application-vnd.geogebra.file.svg") },
        { "gif", new("image/gif", "image-gif.svg") },
        { "go", new("text/plain", "text-x-go.svg") },
        { "gsheet", new("application/vnd.google-apps.spreadsheet", "gdsheet.svg") },
        { "gslides", new("application/vnd.google-apps.presentation", "gdslides.svg") },
        { "gz", new("application/gzip", "application-gzip.svg") },
        { "h", new("text/plain", "text-x-chdr.svg") },
        { "h++", new("text/plain", "text-x-c++hdr.svg") },
        { "hh", new("text/plain", "text-x-c++hdr.svg") },
        { "hpp", new("text/plain", "text-x-c++hdr.svg") },
        { "hs", new("text/plain", "text-x-haskell.svg") },
        { "htm", new("text/html", "text-html.svg") },
        { "html", new("text/html", "text-html.svg") },
        { "hxx", new("text/plain", "text-x-c++hdr.svg") },
        { "icc", new("application/vnd.iccprofile", "application-vnd.iccprofile.svg") },
        { "icm", new("application/vnd.iccprofile", "application-vnd.iccprofile.svg") },
        { "ico", new("image/vnd.microsoft.icon", "image-vnd.microsoft.icon.svg") },
        { "ics", new("text/calendar", "x-office-calendar.svg") },
        { "ini", new("text/plain", "text-x-script.svg") },
        { "iso", new("application/x-iso9660-image", "application-x-cd-image.svg") },
        { "jar", new("application/java-archive", "application-x-java-archive.svg") },
        { "java", new("text/plain", "text-x-java.svg") },
        { "jpeg", new("image/jpeg", "image-jpeg.svg") },
        { "jpg", new("image/jpeg", "image-jpeg.svg") },
        { "js", new("text/javascript", "text-x-javascript.svg") },
        { "jsx", new("text/javascript", "text-x-javascript.svg") },
        { "json", new("application/json", "application-json.svg") },
        { "jsonld", new("application/ld+json", "application-json.svg") },
        { "kt", new("text/plain", "text-x-kotlin.svg") },
        { "less", new("text/plain", "text-less.svg") },
        { "log", new("text/plain", "text-x-generic.svg") },
        { "ltx", new("text/x-tex", "text-x-tex.svg") },
        { "lua", new("text/plain", "text-x-lua.svg") },
        { "m4a", new("audio/mp4", "audio-x-generic.svg") },
        { "ma", new("application/mathematica", "application-mathematica.svg") },
        { "mail", new("message/rfc822", "message-rfc822.svg") },
        { "map", new("application/json", "application-json.svg") },
        { "markdown", new("text/markdown", "text-markdown.svg") },
        { "mb", new("application/mathematica", "application-mathematica.svg") },
        { "mbox", new("application/mbox", "application-mbox.svg") },
        { "md", new("text/markdown", "text-markdown.svg") },
        { "mht", new("message/rfc822", "message-rfc822.svg") },
        { "mhtml", new("message/rfc822", "message-rfc822.svg") },
        { "mid", new("audio/midi", "audio-midi.svg") },
        { "midi", new("audio/midi", "audio-midi.svg") },
        { "mjs", new("text/javascript", "text-x-javascript.svg") },
        { "mkv", new("video/x-matroska", "video-x-generic.svg") },
        { "mov", new("video/quicktime", "video-x-generic.svg") },
        { "mp3", new("audio/mpeg", "audio-x-generic.svg") },
        { "mp4", new("video/mp4", "video-x-generic.svg") },
        { "mpeg", new("video/mpeg", "video-x-generic.svg") },
        { "mpkg", new("application/vnd.apple.installer+xml", "package-x-generic.svg") },
        { "msi", new("application/x-msdownload", "application-x-ms-dos-executable.svg") },
        { "msp", new("application/octet-stream", "application-octet-stream.svg") },
        { "msu", new("application/octet-stream", "application-octet-stream.svg") },
        { "nws", new("message/rfc822", "message-rfc822.svg") },
        { "o", new("application/x-object", "application-x-object.svg") },
        { "obj", new("application/x-object", "application-x-object.svg") },
        { "odc", new("application/vnd.oasis.opendocument.chart", "application-vnd.oasis.opendocument.chart.svg") },
        { "odf", new("application/vnd.oasis.opendocument.formula", "application-vnd.oasis.opendocument.formula.svg") },
        { "odp", new("application/vnd.oasis.opendocument.presentation", "application-vnd.oasis.opendocument.presentation.svg") },
        { "ods", new("application/vnd.oasis.opendocument.spreadsheet", "application-vnd.oasis.opendocument.spreadsheet.svg") },
        { "odt", new("application/vnd.oasis.opendocument.text", "application-vnd.oasis.opendocument.text.svg") },
        { "oga", new("audio/ogg", "audio-x-generic.svg") },
        { "ogg", new("audio/ogg", "application-ogg.svg") },
        { "ogv", new("video/ogg", "video-x-generic.svg") },
        { "ogx", new("application/ogg", "application-ogg.svg") },
        { "old", new("application/x-trash", "application-x-trash.svg") },
        { "opus", new("audio/opus", "audio-x-generic.svg") },
        { "otc", new("application/vnd.oasis.opendocument.chart-template", "application-vnd.oasis.opendocument.chart-template.svg") },
        { "otf", new("font/otf", "font-x-generic.svg") },
        { "otp", new("application/vnd.oasis.opendocument.presentation-template", "application-vnd.oasis.opendocument.presentation-template.svg") },
        { "ots", new("application/vnd.oasis.opendocument.spreadsheet-template", "application-vnd.oasis.opendocument.spreadsheet-template.svg") },
        { "ott", new("application/vnd.oasis.opendocument.text-template", "application-vnd.oasis.opendocument.text-template.svg") },
        { "ova", new("application/x-virtualbox-ova", "virtualbox-ova.svg") },
        { "ovf", new("application/x-virtualbox-ovf", "virtualbox-ovf.svg") },
        { "p", new("text/x-pascal", "text-x-pascal.svg") },
        { "pas", new("text/x-pascal", "text-x-pascal.svg") },
        { "pdf", new("application/pdf", "application-pdf.svg") },
        { "php", new("application/x-httpd-php", "application-x-php.svg") },
        { "pl", new("text/x-perl", "application-x-perl.svg") },
        { "pm", new("text/x-perl", "application-x-perl.svg") },
        { "png", new("image/png", "image-png.svg") },
        { "pot", new("application/vnd.ms-powerpoint", "application-vnd.ms-powerpoint.svg") },
        { "ppa", new("application/vnd.ms-powerpoint", "application-vnd.ms-powerpoint.svg") },
        { "pps", new("application/vnd.ms-powerpoint", "application-vnd.ms-powerpoint.svg") },
        { "ppt", new("application/vnd.ms-powerpoint", "application-vnd.ms-powerpoint.svg") },
        { "pptx", new("application/vnd.openxmlformats-officedocument.presentationml.presentation", "application-vnd.openxmlformats-officedocument.presentationml.presentation.svg") },
        { "ps", new("application/postscript", "application-postscript.svg") },
        { "psd", new("image/vnd.adobe.photoshop", "application-photoshop.svg") },
        { "pwz", new("application/vnd.ms-powerpoint", "application-vnd.ms-powerpoint.svg") },
        { "py", new("text/plain", "text-x-python.svg") },
        { "r", new("text/plain", "text-x-r.svg") },
        { "rar", new("application/vnd.rar", "application-x-rar.svg") },
        { "rb", new("text/plain", "text-x-ruby.svg") },
        { "rpm", new("application/x-rpm", "application-x-rpm.svg") },
        { "rs", new("text/plain", "text-rust.svg") },
        { "rtf", new("application/rtf", "text-richtext.svg") },
        { "rtx", new("text/richtext", "text-richtext.svg") },
        { "sass", new("text/x-sass", "text-x-sass.svg") },
        { "scala", new("text/plain", "text-x-scala.svg") },
        { "sh", new("application/x-sh", "application-x-shellscript.svg") },
        { "shtml", new("text/html", "text-html.svg") },
        { "sig", new("application/pgp-signature", "application-pgp-signature.svg") },
        { "sik", new("application/x-trash", "application-x-trash.svg") },
        { "so", new("application/x-sharedlib", "application-x-sharedlib.svg") },
        { "sql", new("application/sql", "application-sql.svg") },
        { "srt", new("application/x-subrip", "application-x-subrip.svg") },
        { "sty", new("text/x-tex", "text-x-tex.svg") },
        { "svg", new("image/svg+xml", "image-svg+xml.svg") },
        { "svgz", new("image/svg+xml", "image-svg+xml.svg") },
        { "swf", new("application/x-shockwave-flash", "x-content-software.svg") },
        { "tar", new("application/x-tar", "application-x-tar.svg") },
        { "tcl", new("text/x-tcl", "text-x-tcl.svg") },
        { "tex", new("text/x-tex", "text-x-tex.svg") },
        { "tga", new("image/x-tga", "image-x-tga.svg") },
        { "tif", new("image/tiff", "image-tiff.svg") },
        { "tiff", new("image/tiff", "image-tiff.svg") },
        { "tk", new("text/x-tcl", "text-x-tcl.svg") },
        { "toml", new("text/plain", "application-toml.svg") },
        { "torrent", new("application/x-bittorrent", "application-torrent.svg") },
        { "ts", new("text/javascript", "text-x-typescript.svg") },
        { "tsx", new("text/javascript", "text-x-typescript.svg") },
        { "ttf", new("font/ttf", "font-x-generic.svg") },
        { "txt", new("text/plain", "text-x-generic.svg") },
        { "vala", new("text/plain", "text-x-vala.svg") },
        { "vbox", new("application/x-virtualbox-vbox", "virtualbox-vbox.svg") },
        { "vdi", new("application/x-virtualbox-vdi", "virtualbox-vdi.svg") },
        { "vhd", new("application/x-virtualbox-vhd", "virtualbox-vhd.svg") },
        { "vmdk", new("application/x-virtualbox-vmdk", "virtualbox-vmdk.svg") },
        { "vsd", new("application/vnd.visio", "application-vnd.visio.svg") },
        { "vss", new("application/vnd.visio", "application-vnd.visio.svg") },
        { "vst", new("application/vnd.visio", "application-vnd.visio.svg") },
        { "vsw", new("application/vnd.visio", "application-vnd.visio.svg") },
        { "vue", new("text/plain", "text-html.svg") },
        { "wav", new("audio/wav", "audio-x-generic.svg") },
        { "weba", new("audio/webm", "audio-x-generic.svg") },
        { "webm", new("video/webm", "video-x-generic.svg") },
        { "webp", new("image/webp", "image-webp.svg") },
        { "woff", new("font/woff", "font-x-generic.svg") },
        { "woff2", new("font/woff2", "font-x-generic.svg") },
        { "xhtml", new("application/xhtml+xml", "text-html.svg") },
        { "xla", new("application/vnd.ms-excel", "application-vnd.ms-excel.svg") },
        { "xlb", new("application/vnd.ms-excel", "application-vnd.ms-excel.svg") },
        { "xlc", new("application/vnd.ms-excel", "application-vnd.ms-excel.svg") },
        { "xlm", new("application/vnd.ms-excel", "application-vnd.ms-excel.svg") },
        { "xls", new("application/vnd.ms-excel", "application-vnd.ms-excel.svg") },
        { "xlsx", new("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application-vnd.openxmlformats-officedocument.spreadsheetml.sheet.svg") },
        { "xlt", new("application/vnd.ms-excel", "application-vnd.ms-excel.svg") },
        { "xltx", new("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "application-vnd.openxmlformats-officedocument.spreadsheetml.template.svg") },
        { "xlw", new("application/vnd.ms-excel", "application-vnd.ms-excel.svg") },
        { "xml", new("application/xml", "text-xml.svg") },
        { "xul", new("application/vnd.mozilla.xul+xml", "application-x-addon.svg") },
        { "yaml", new("text/yaml", "application-x-yaml.svg") },
        { "yml", new("text/yaml", "application-x-yaml.svg") },
        { "zip", new("application/zip", "application-zip.svg") },
        { "zst", new("application/zstd", "application-zstd.svg") },
        { "~", new("application/x-trash", "application-x-trash.svg") }
    };

    public static bool CanHandle(string fileName)
    {
        var extension = Path.GetExtension(fileName).Trim('.');
        var contentType = GetContentType(extension);
        return contentType != "application/octet-stream";
    }

    public static bool IsVideo(string fileName)
    {
        var extension = Path.GetExtension(fileName).Trim('.');
        var contentType = GetContentType(extension);
        return contentType.StartsWith("video");
    }

    public static string GetContentType(string extenstion)
    {
        var lower = extenstion.ToLower().TrimStart('.');
        if (ExtensionMap.TryGetValue(lower, out var mapping))
        {
            return mapping.ContentType;
        }
        return "application/octet-stream";
    }

    public static string GetIcon(string fileName)
    {
        var extension = Path.GetExtension(fileName).TrimStart('.').ToLower();
        if (ExtensionMap.TryGetValue(extension, out var mapping))
        {
            return mapping.Icon;
        }
        return "unknown.svg";
    }
}