namespace Aiursoft.CSTools.Models;

public static class Mime
{
    private static readonly Dictionary<string, string> MimeTypesDictionary = new()
    {
        { "%", "application/x-trash" },
        { "7z", "application/x-archive" },
        { "a", "application/octet-stream" },
        { "ai", "application/postscript" },
        { "apk", "application/apk" },
        { "art", "message/rfc822" },
        { "avi", "video/x-generic" },
        { "bak", "application/x-trash" },
        { "bin", "application/octet-stream" },
        { "blend", "application/x-blender" },
        { "bmp", "application/image-bmp" },
        { "bz2", "application/x-bzip" },
        { "c", "text/x-c" },
        { "cab", "application/vnd.ms-cab-compressed" },
        { "chm", "application/vnd.ms-htmlhelp" },
        { "class", "application/x-java" },
        { "cls", "text/x-tex" },
        { "cmake", "text/x-cmake" },
        { "coffee", "application/vnd.coffeescript" },
        { "cpp", "text/x-cpp" },
        { "cs", "text/x-csharp" },
        { "css", "text/css" },
        { "dcm", "application/dicom" },
        { "deb", "application/x-deb" },
        { "deploy", "application/octet-stream" },
        { "djv", "image/vnd.djvu" },
        { "djvu", "image/vnd.djvu" },
        { "dll", "application/x-sharedlib" },
        { "doc", "application/vnd.ms-word" },
        { "dockerfile", "text/dockerfile" },
        { "docx", "application/vnd.ms-word" },
        { "dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template" },
        { "dwg", "image/vnd.dwg" },
        { "eml", "message/rfc822" },
        { "eps", "application/postscript" },
        { "eps2", "application/postscript" },
        { "eps3", "application/postscript" },
        { "epsf", "application/postscript" },
        { "epsi", "application/postscript" },
        { "epub", "application/epub+zip" },
        { "exe", "application/x-ms-dos-executable" },
        { "f", "text/x-fortran" },
        { "f90", "text/x-fortran" },
        { "flac", "audio/x-generic" },
        { "flatpak", "application/vnd.flatpak" },
        { "ggb", "application/vnd.geogebra.file" },
        { "gif", "application/image-gif" },
        { "go", "text/x-go" },
        { "gz", "application/x-gzip" },
        { "h", "text/x-chdr" },
        { "h++", "text/x-c++hdr" },
        { "hh", "text/x-c++hdr" },
        { "hpp", "text/x-c++hdr" },
        { "hs", "text/x-haskell" },
        { "htm", "text/html" },
        { "html", "text/html" },
        { "hxx", "text/x-c++hdr" },
        { "icc", "application/vnd.iccprofile" },
        { "icm", "application/vnd.iccprofile" },
        { "ico", "application/image-ico" },
        { "iso", "application/x-cd-image" },
        { "jar", "application/x-java-archive" },
        { "java", "text/x-java" },
        { "jpeg", "application/image-jpg" },
        { "jpg", "application/image-jpg" },
        { "js", "text/x-javascript" },
        { "json", "application/json" },
        { "kt", "text/x-kotlin" },
        { "less", "text/less" },
        { "ltx", "text/x-tex" },
        { "lua", "text/x-lua" },
        { "m4a", "audio/x-generic" },
        { "ma", "application/mathematica" },
        { "mail", "message/rfc822" },
        { "markdown", "text/markdown" },
        { "mb", "application/mathematica" },
        { "mbox", "application/mbox" },
        { "md", "text/markdown" },
        { "mht", "message/rfc822" },
        { "mhtml", "message/rfc822" },
        { "mkv", "video/x-generic" },
        { "mov", "video/x-generic" },
        { "mp3", "audio/x-generic" },
        { "mp4", "video/x-generic" },
        { "msi", "application/x-ms-dos-executable" },
        { "msp", "application/octet-stream" },
        { "msu", "application/octet-stream" },
        { "nws", "message/rfc822" },
        { "o", "application/x-object" },
        { "obj", "application/x-object" },
        { "odc", "application/vnd.oasis.opendocument.chart" },
        { "odf", "application/vnd.oasis.opendocument.formula" },
        { "ogg", "application/ogg" },
        { "ogv", "video/x-generic" },
        { "ogx", "application/ogg" },
        { "old", "application/x-trash" },
        { "otc", "application/vnd.oasis.opendocument.chart-template" },
        { "otf", "font/x-generic" },
        { "otp", "application/vnd.oasis.opendocument.presentation-template" },
        { "ots", "application/vnd.oasis.opendocument.spreadsheet-template" },
        { "ott", "application/vnd.oasis.opendocument.text-template" },
        { "p", "text/x-pascal" },
        { "pas", "text/x-pascal" },
        { "pdf", "application/pdf" },
        { "php", "text/x-php" },
        { "pl", "application/x-perl" },
        { "pm", "application/x-perl" },
        { "png", "image/x-generic" },
        { "pot", "application/vnd.ms-powerpoint" },
        { "ppa", "application/vnd.ms-powerpoint" },
        { "pps", "application/vnd.ms-powerpoint" },
        { "ppt", "application/vnd.ms-powerpoint" },
        { "pptx", "application/vnd.ms-powerpoint" },
        { "ps", "application/postscript" },
        { "pwz", "application/vnd.ms-powerpoint" },
        { "py", "text/x-python" },
        { "r", "text/x-r" },
        { "rar", "application/x-rar" },
        { "rb", "text/x-ruby" },
        { "rpm", "application/x-rpm" },
        { "rs", "text/rust" },
        { "rtx", "text/richtext" },
        { "sass", "text/x-sass" },
        { "scala", "text/x-scala" },
        { "sh", "application/x-shellscript" },
        { "shtml", "text/html" },
        { "sig", "application/pgp-signature" },
        { "sik", "application/x-trash" },
        { "so", "application/x-sharedlib" },
        { "sql", "application/sql" },
        { "srt", "application/x-subrip" },
        { "sty", "text/x-tex" },
        { "svg", "image/svg+xml" },
        { "svgz", "image/svg+xml" },
        { "tar", "application/x-tar" },
        { "tcl", "text/x-tcl" },
        { "tex", "text/x-tex" },
        { "tga", "application/image-tga" },
        { "tif", "application/image-tiff" },
        { "tiff", "application/image-tiff" },
        { "tk", "text/x-tcl" },
        { "toml", "application/toml" },
        { "torrent", "application/x-bittorrent" },
        { "ts", "text/x-typescript" },
        { "ttf", "font/x-generic" },
        { "txt", "text/x-generic" },
        { "vala", "text/x-vala" },
        { "vsd", "application/vnd.visio" },
        { "vss", "application/vnd.visio" },
        { "vst", "application/vnd.visio" },
        { "vsw", "application/vnd.visio" },
        { "wav", "audio/x-generic" },
        { "webm", "video/x-generic" },
        { "webp", "image/webp" },
        { "woff", "font/x-generic" },
        { "woff2", "font/x-generic" },
        { "xla", "application/vnd.ms-excel" },
        { "xlb", "application/vnd.ms-excel" },
        { "xlc", "application/vnd.ms-excel" },
        { "xlm", "application/vnd.ms-excel" },
        { "xls", "application/vnd.ms-excel" },
        { "xlsx", "application/vnd.ms-excel" },
        { "xlt", "application/vnd.ms-excel" },
        { "xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template" },
        { "xlw", "application/vnd.ms-excel" },
        { "xml", "text/xml" },
        { "yaml", "application/x-yaml" },
        { "yml", "application/x-yaml" },
        { "zip", "application/x-zip" },
        { "zst", "application/zstd" },
        { "~", "application/x-trash" },
    };

    private static bool HasKey(string extension)
    {
        var lower = extension.ToLower().TrimStart('.');
        return MimeTypesDictionary.ContainsKey(lower);
    }

    public static bool CanHandle(string fileName)
    {
        var extension = Path.GetExtension(fileName).Trim('.');
        var contentType = GetContentType(extension);
        return contentType != "application/octet-stream";
    }

    public static bool IsVideo(string fileName)
    {
        var extension = Path.GetExtension(fileName).Trim('.');
        var contentType = GetContentType(extension);
        return contentType.StartsWith("video");
    }

    public static string GetContentType(string extenstion)
    {
        //Not to download the file, and we can process the file, let us process it.
        if (!HasKey(extenstion))
        {
            return "application/octet-stream";
        }

        var lower = extenstion.ToLower().TrimStart('.');
        return MimeTypesDictionary[lower];
    }
}